#!/usr/bin/env bash
#MISE description="Lint the project"
#USAGE flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
  (cd $MISE_PROJECT_ROOT && mix format)
else
    (cd $MISE_PROJECT_ROOT && mix format --check-formatted)
    (cd $MISE_PROJECT_ROOT && mix credo)
fi
